name: Deploy GitHub Pages (Next.js static export)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Required permissions for actions/deploy-pages
# Ref: https://github.com/actions/deploy-pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Enables Pages and provides metadata; safe to run in all builds
      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Install dependencies (Yarn via Corepack)
        run: |
          corepack enable
          corepack install
          yarn --immutable

      # Build and export static site
      - name: Build site
        run: |
          yarn build
          # Ensure 404.html exists for SPA deep links (Next already creates one)
          if [ -f out/index.html ] && [ ! -f out/404.html ]; then
            cp out/index.html out/404.html
          fi

      # Upload the built static site for Pages to deploy
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

name: Deploy GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Required permissions for actions/deploy-pages
# Ref: https://github.com/actions/deploy-pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Enables Pages and provides metadata; safe to run in all builds
      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Install dependencies (yarn)
        run: |
          corepack enable
          corepack install || true
          yarn install --immutable

      # Build the Vite app from the repo root
      - name: Build site
        env:
          # Custom domain/user site: serve from root
          BASE_PATH: /
        run: |
          yarn build
          # SPA deep links: serve index.html for unknown routes
          if [ -f dist/index.html ]; then
            cp dist/index.html dist/404.html
          fi

      # Upload the built static site for Pages to deploy
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


